#!/bin/sh

lb config noauto \
	--debian-installer-gui=true --debian-installer=live \
	-d stable --debian-installer-distribution stable \
	--archive-areas "main non-free-firmware" \
	--parent-archive-areas "main non-free-firmware" \
	"${@}"

